"""empty message

Revision ID: 713130df034c
Revises: 24d2b5d14d80
Create Date: 2017-03-14 16:02:56.930610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '713130df034c'
down_revision = '24d2b5d14d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('pic', sa.String(length=80), nullable=True))
    op.drop_column('user_profile', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'pic')
    # ### end Alembic commands ###
